#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
http://amoffat.github.io/sh/sections/asynchronous_execution.html
https://www.cyberciti.biz/faq/python-execute-unix-linux-command-examples/
Created on Fri May 19 12:47:56 2017

@author: marius
"""
import sh
import os
from sh import xrandr
# uso una funcion para salvaguardar la resolución en uso

def storeCurrentResolution():
    
    Xaxis = os.popen("xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1")
    readXaxis = Xaxis.read()
    
    Yaxis = os.popen("xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2")
    readYaxis = Yaxis.read()
    
    resolutionBackup = str(readXaxis)+"x"+str(readYaxis)
    return resolutionBackup

storeCurrentResolution()
    
    
#uso esta función para revertir los cambios
def revertChanges(resolutionBackup):
    
    xrandr("-s", resolutionBackup)
    

    
    
   


def changeResolution():
    return Null




resolution = os.popen("cvt 1440 900")

data = resolution.read()
print(data)
